export const WILAYAS = [
  "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Béjaïa", "Biskra",
  "Béchar", "Blida", "Bouira", "Tamanrasset", "Tébessa", "Tlemcen", "Tiaret",
  "Tizi Ouzou", "Alger", "Djelfa", "Jijel", "Sétif", "Saïda", "Skikda",
  "Sidi Bel Abbès", "Annaba", "Guelma", "Constantine", "Médéa", "Mostaganem",
  "M'Sila", "Mascara", "Ouargla", "Oran", "El Bayadh", "Illizi", "Bordj Bou Arréridj",
  "Boumerdès", "El Tarf", "Tindouf", "Tissemsilt", "El Oued", "Khenchela",
  "Souk Ahras", "Tipaza", "Mila", "Aïn Defla", "Naâma", "Aïn Témouchent",
  "Ghardaïa", "Relizane", "Timimoun", "Bordj Badji Mokhtar", "Ouled Djellal",
  "Béni Abbès", "In Salah", "In Guezzam", "Touggourt", "Djanet", "M'Ghair", "El Meniaa"
];

export const PROPERTY_TYPES = [
  { value: "apartment", label: { en: "Apartment", fr: "Appartement", ar: "شقة" } },
  { value: "house", label: { en: "House", fr: "Maison", ar: "منزل" } },
  { value: "villa", label: { en: "Villa", fr: "Villa", ar: "فيلا" } },
  { value: "land", label: { en: "Land", fr: "Terrain", ar: "أرض" } },
  { value: "commercial", label: { en: "Commercial", fr: "Commercial", ar: "تجاري" } },
  { value: "new_development", label: { en: "New Development", fr: "Programme Neuf", ar: "مشروع جديد" } },
  { value: "office", label: { en: "Office", fr: "Bureau", ar: "مكتب" } },
  { value: "farm", label: { en: "Farm", fr: "Ferme", ar: "مزرعة" } }
];

export const FEATURES_LIST = [
  "Parking", "Garage", "Garden", "Terrace", "Balcony", "Pool",
  "Elevator", "Security", "Air Conditioning", "Heating", "Solar Panels",
  "Well", "Concierge", "Interphone", "Double Glazing", "Cave"
];

export const TRANSLATIONS = {
  en: {
    siteName: "Dari",
    tagline: "Find Your Dream Home in Algeria",
    search: "Search",
    buy: "Buy",
    rent: "Rent",
    sell: "Sell",
    postListing: "Post a Listing",
    favorites: "Favorites",
    messages: "Messages",
    myListings: "My Listings",
    allWilayas: "All Wilayas",
    allTypes: "All Types",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    minArea: "Min Area",
    results: "results",
    featured: "Featured",
    price: "Price",
    area: "Area",
    rooms: "Rooms",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    contact: "Contact",
    sendMessage: "Send Message",
    saveSearch: "Save Search",
    sortBy: "Sort by",
    newest: "Newest",
    priceAsc: "Price: Low to High",
    priceDesc: "Price: High to Low",
    noResults: "No listings found",
    loading: "Loading...",
    wilaya: "Wilaya",
    commune: "Commune",
    propertyType: "Property Type",
    listingType: "Listing Type",
    description: "Description",
    features: "Features & Amenities",
    location: "Location",
    contactSeller: "Contact Seller",
    similarListings: "Similar Listings",
    perMonth: "/ month",
    perYear: "/ year",
    dzd: "DZD",
    m2: "m²",
    floor: "Floor",
    yearBuilt: "Year Built",
    furnished: "Furnished",
    viewDetails: "View Details",
    addToFavorites: "Save",
    removeFromFavorites: "Saved",
    share: "Share",
    home: "Home",
    signIn: "Sign In",
    signOut: "Sign Out",
    myAccount: "My Account",
    sale: "For Sale",
    forRent: "For Rent",
    nameLabel: "Full Name",
    phoneLabel: "Phone Number",
    emailLabel: "Email",
    messageLabel: "Your Message",
    submit: "Submit",
    titleLabel: "Listing Title",
    priceLabel: "Price (DZD)",
    areaLabel: "Area (m²)",
    addressLabel: "Address",
    imagesLabel: "Photos",
    publishListing: "Publish Listing",
    editListing: "Edit",
    deleteListing: "Delete",
    activeListings: "Active Listings",
    hero_subtitle: "Algeria's #1 real estate platform"
  },
  fr: {
    siteName: "Dari",
    tagline: "Trouvez Votre Bien Idéal en Algérie",
    search: "Rechercher",
    buy: "Acheter",
    rent: "Louer",
    sell: "Vendre",
    postListing: "Publier une Annonce",
    favorites: "Favoris",
    messages: "Messages",
    myListings: "Mes Annonces",
    allWilayas: "Toutes les Wilayas",
    allTypes: "Tous les Types",
    minPrice: "Prix Min",
    maxPrice: "Prix Max",
    minArea: "Surface Min",
    results: "résultats",
    featured: "En Vedette",
    price: "Prix",
    area: "Surface",
    rooms: "Pièces",
    bedrooms: "Chambres",
    bathrooms: "Salles de bain",
    contact: "Contact",
    sendMessage: "Envoyer un message",
    saveSearch: "Sauvegarder la recherche",
    sortBy: "Trier par",
    newest: "Plus récent",
    priceAsc: "Prix Croissant",
    priceDesc: "Prix Décroissant",
    noResults: "Aucune annonce trouvée",
    loading: "Chargement...",
    wilaya: "Wilaya",
    commune: "Commune",
    propertyType: "Type de Bien",
    listingType: "Type d'Annonce",
    description: "Description",
    features: "Caractéristiques",
    location: "Localisation",
    contactSeller: "Contacter le Vendeur",
    similarListings: "Annonces Similaires",
    perMonth: "/ mois",
    perYear: "/ an",
    dzd: "DA",
    m2: "m²",
    floor: "Étage",
    yearBuilt: "Année de construction",
    furnished: "Meublé",
    viewDetails: "Voir Détails",
    addToFavorites: "Sauvegarder",
    removeFromFavorites: "Sauvegardé",
    share: "Partager",
    home: "Accueil",
    signIn: "Connexion",
    signOut: "Déconnexion",
    myAccount: "Mon Compte",
    sale: "À Vendre",
    forRent: "À Louer",
    nameLabel: "Nom Complet",
    phoneLabel: "Numéro de Téléphone",
    emailLabel: "Email",
    messageLabel: "Votre Message",
    submit: "Envoyer",
    titleLabel: "Titre de l'Annonce",
    priceLabel: "Prix (DA)",
    areaLabel: "Surface (m²)",
    addressLabel: "Adresse",
    imagesLabel: "Photos",
    publishListing: "Publier l'Annonce",
    editListing: "Modifier",
    deleteListing: "Supprimer",
    activeListings: "Annonces Actives",
    hero_subtitle: "La 1ère plateforme immobilière d'Algérie"
  },
  ar: {
    siteName: "داري",
    tagline: "ابحث عن منزل أحلامك في الجزائر",
    search: "بحث",
    buy: "شراء",
    rent: "إيجار",
    sell: "بيع",
    postListing: "نشر إعلان",
    favorites: "المفضلة",
    messages: "الرسائل",
    myListings: "إعلاناتي",
    allWilayas: "كل الولايات",
    allTypes: "كل الأنواع",
    minPrice: "السعر الأدنى",
    maxPrice: "السعر الأقصى",
    minArea: "المساحة الدنيا",
    results: "نتيجة",
    featured: "مميز",
    price: "السعر",
    area: "المساحة",
    rooms: "الغرف",
    bedrooms: "غرف النوم",
    bathrooms: "الحمامات",
    contact: "تواصل",
    sendMessage: "إرسال رسالة",
    saveSearch: "حفظ البحث",
    sortBy: "ترتيب حسب",
    newest: "الأحدث",
    priceAsc: "السعر: من الأقل",
    priceDesc: "السعر: من الأعلى",
    noResults: "لا توجد إعلانات",
    loading: "جار التحميل...",
    wilaya: "الولاية",
    commune: "البلدية",
    propertyType: "نوع العقار",
    listingType: "نوع الإعلان",
    description: "الوصف",
    features: "المميزات والمرافق",
    location: "الموقع",
    contactSeller: "تواصل مع البائع",
    similarListings: "إعلانات مشابهة",
    perMonth: "/ شهر",
    perYear: "/ سنة",
    dzd: "دج",
    m2: "م²",
    floor: "الطابق",
    yearBuilt: "سنة البناء",
    furnished: "مفروش",
    viewDetails: "عرض التفاصيل",
    addToFavorites: "حفظ",
    removeFromFavorites: "محفوظ",
    share: "مشاركة",
    home: "الرئيسية",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    myAccount: "حسابي",
    sale: "للبيع",
    forRent: "للإيجار",
    nameLabel: "الاسم الكامل",
    phoneLabel: "رقم الهاتف",
    emailLabel: "البريد الإلكتروني",
    messageLabel: "رسالتك",
    submit: "إرسال",
    titleLabel: "عنوان الإعلان",
    priceLabel: "السعر (دج)",
    areaLabel: "المساحة (م²)",
    addressLabel: "العنوان",
    imagesLabel: "الصور",
    publishListing: "نشر الإعلان",
    editListing: "تعديل",
    deleteListing: "حذف",
    activeListings: "الإعلانات النشطة",
    hero_subtitle: "المنصة العقارية الأولى في الجزائر"
  }
};

// Re-export from price.config.js — single source of truth
export { formatPrice } from "./price.config";

export function getLabel(item, lang) {
  if (!item || !item.label) return "";
  return item.label[lang] || item.label.fr || item.value;
}