export const HEATING_TYPE_OPTIONS = [
  { value: "gaz_de_ville",
    label: { fr: "Gaz de ville",
             en: "City gas",
             ar: "غاز المدينة" } },
  { value: "gaz_butane",
    label: { fr: "Gaz butane",
             en: "Bottle gas",
             ar: "غاز البوتان" } },
  { value: "electrique",
    label: { fr: "Électrique",
             en: "Electric",
             ar: "كهرباء" } },
  { value: "mazout",
    label: { fr: "Mazout",
             en: "Oil heating",
             ar: "مازوت" } },
  { value: "climatisation_reversible",
    label: { fr: "Climatisation réversible",
             en: "Reversible AC",
             ar: "تكييف عكسي" } },
  { value: "aucun",
    label: { fr: "Aucun",
             en: "None",
             ar: "لا يوجد" } },
];